--
--      Copyright (C) 2009-2010   Matt Jadud
--      Copyright (C)      2010   Michael Andrew Pirrone-Brusse
--
--	This library is free software; you can redistribute it and/or
--	modify it under the terms of the GNU Lesser General Public
--	License as published by the Free Software Foundation; either
--	version 2 of the License, or (at your option) any later version.
--
--	This library is distributed in the hope that it will be useful,
--	but WITHOUT ANY WARRANTY; without even the implied warranty of
--	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
--	Lesser General Public License for more details.
--
--      You should have received a copy of the GNU General Public License
--      along with this program.  If not, see <http://www.gnu.org/licenses/>.
--
--** A wrapper for platform-specific code on the ATmega328.
--
-- @module 328.avr

#IF NOT (DEFINED (AVR.MODULE))
#DEFINE AVR.MODULE

-- base, constants, and FFI must come first
#INCLUDE "base.module"
#INCLUDE "constants.module"
-- Maps pin numbers 1 - 28 to registers
#INCLUDE "chipmap.module"
#INCLUDE "ffi.module"
-- These modules depend on base, constants, and FFI
#INCLUDE "pin.module"
#INCLUDE "usart.module"
#INCLUDE "adc.module"
#INCLUDE "pwm.common.module"
#INCLUDE "external.interrupts.module"

#ENDIF
