--** A wrapper for platform-specific code on the ATmega328.
-- @module 328.avr

#IF NOT (DEFINED (AVR.MODULE))
#DEFINE AVR.MODULE

-- base, constants, and FFI must come first
#INCLUDE "base.module"
#INCLUDE "constants.module"
-- Maps pin numbers 1 - 28 to registers
#INCLUDE "chipmap.module"
#INCLUDE "ffi.module"
-- These modules depend on base, constants, and FFI
#INCLUDE "pin.module"
#INCLUDE "usart.module"
#INCLUDE "adc.module"
#INCLUDE "pwm.common.module"
#INCLUDE "external.interrupts.module"

#ENDIF
