--
--	Copyright (C) 2009-2010   Christian Jacobsen
--      Copyright (C) 2009-2010   Matt Jadud
--      Copyright (C)      2010   Michael Andrew Pirrone-Brusse
--      Copyright (C) 2009-2010   Adam Sampson
--
--	This library is free software; you can redistribute it and/or
--	modify it under the terms of the GNU Lesser General Public
--	License as published by the Free Software Foundation; either
--	version 2 of the License, or (at your option) any later version.
--
--	This library is distributed in the hope that it will be useful,
--	but WITHOUT ANY WARRANTY; without even the implied warranty of
--	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
--	Lesser General Public License for more details.
--
--      You should have received a copy of the GNU General Public License
--      along with this program.  If not, see <http://www.gnu.org/licenses/>.
--
--** Symbolic arrays and FUNCTON(s) for mapping into General Purpose I/O
-- functionality on ATmega328 based boards.
--
-- @module 328.chipmap

#IF NOT (DEFINED (CHIPMAP.MODULE))
#DEFINE CHIPMAP.MODULE

-- From Atmel document 8271S

-- PIN     REG     PIN    REG
--   1     PC6      15    PB1
--   2     PD0      16    PB2
--   3     PD1      17    PB3
--   4     PD2      18    PB4
--   5     PD3      19    PB5
--   6     PD4      20    AVcc
--   7     Vcc      21    AREF
--   8     GND      22    GND
--   9     PB6      23    PC0
--  10     PB7      24    PC1
--  11     PD5      25    PC2
--  12     PD6      26    PC3
--  13     PD7      27    PC4
--  14     PB0      28    PC5

VAL INT DDRX  IS -1:
VAL INT PORTX IS -1:
VAL INT PINX  IS -1:

--------- DDR.MAP --------------------------------------------
--                       0                                   7
VAL []INT DDR.MAP IS [DDRC, DDRD, DDRD, DDRD, DDRD, DDRD, DDRX,
--                       8                                  14
                      DDRX, DDRB, DDRD, DDRD, DDRD, DDRD, DDRB,
--                      15                                  21
                      DDRB, DDRB, DDRB, DDRB, DDRB, DDRX, DDRX,
--                      22                                  27
                      DDRX, DDRC, DDRC, DDRC, DDRC, DDRC, DDRC]:

--------- PORT.MAP ---------------------------------------------------
--                         0                                         7
VAL []INT PORT.MAP IS [PORTC, PORTD, PORTD, PORTD, PORTD, PORTD, PORTX,
--                         8                                        14
                       PORTX, PORTB, PORTD, PORTD, PORTD, PORTD, PORTB,
--                        15                                        21
                       PORTB, PORTB, PORTB, PORTB, PORTB, PORTX, PORTX,
--                        22                                        27
                       PORTX, PORTC, PORTC, PORTC, PORTC, PORTC, PORTC]:

--------- PIN.MAP ---------------------------------------------------
--                       0                                   7
VAL []INT PIN.MAP IS [PINC, PIND, PIND, PIND, PIND, PIND, PINX,
--                       8                                  14
                      PINX, PINB, PIND, PIND, PIND, PIND, PINB,
--                      15                                  21
                      PINB, PINB, PINB, PINB, PINB, PINX, PINX,
--                      22                                  27
                      PINX, PINC, PINC, PINC, PINC, PINC, PINC]:

--------- BIT.MAP ---------------------------------------------------
--                     0                       7
VAL []INT BIT.MAP IS [ 6,  0,  1,  2,  3,  4, -1,
--                     8,                     14
                      -1,  6,  7,  5,  6,  7,  0,
--                    15                      21
                       1,  2,  3,  4,  5, -1, -1,
--                    22                      28
                      -1,  0,  1,  2,  3,  4,  5]: 

--FIXME: mjadud It would be nice if this wasn't duplicated in each architecture

--* Looks up the various General Purpose I/O registers connected to the given
-- [@em AVR] pin.
--
-- @param avr.pin The [@em AVR] pin controlled by the given returns.
-- @returns ddr, port, pin The various control registers that effects the
--   behavior of the given pin.
-- @return bit The specific bit of the control registers that alters the
--   behavior of the given AVR pin.
INT, INT, INT, INT FUNCTION chip.to.gpio (VAL INT avr.pin) 
  INT ddr, port, pin, bit:
  VALOF
    SEQ
      -- AVR pins are numbered starting from 1...
      -- We need to subtract 1 to index into the arrays.
      ddr  := DDR.MAP[avr.pin - 1]
      port := PORT.MAP[avr.pin - 1]
      pin  := PIN.MAP[avr.pin - 1]
      bit  := BIT.MAP[avr.pin - 1]
    RESULT ddr, port, pin, bit
:

#ENDIF
