#!/bin/bash 

# Source in everything we need--both the KRoC env and 
# variables for Arduino compilation and upload.
PLUMB=plumb

source avr-kroc-setup.sh

# This is now plaform-specificly sourced.
# source arduinocc-environment.sh
PLATFORMS=arduino arduinomega seeedmega

if [ "$1" == "" ]; then
	echo
	echo "Choose a platform:"
	for P in $PLATFORMS
	do
		echo "  " $P
	done
	exit
fi	

PLATFORM=$1
source $PLATFORM.conf

# Sanity check
if [ "$2" == "" ]; then
  # Print reasonable documentation for the students
  echo
  echo "No port provided. On Ubuntu Linux, this is probably '/dev/ttyUSB0'."
  echo
  exit
fi

UPLOAD_PORT=$2

if [ "$3" == "firmware" ]; then
  echo "Uploading Transterpreter Virtual Machine"
  avrdude -C $TVM_AVRDUDE_CONF \
     $TVM_AVRDUDE_FIRMWARE_FLAGS \
    -P $1 -b $TVM_UPLOAD_RATE -c stk500v1 \
    -U flash:w:$TVM_ARDUINO_FIRMWARE
  exit
fi

if [ "$3" == "" ]; then
  # Print that they need the filename
  echo
  echo "You need to provide an occam program after the port."
  echo "For example:"
  echo
  echo "  $PLUMB arduino /dev/ttyUSB0 blink.occ"
  echo
  echo "occam programs always end with a .occ extension."
  echo
  exit
fi

FILENAME=$3

PROGBASE=`basename $FILENAME .occ`
PROGDIR=`dirname $FILENAME`
OCC="$PROGDIR/$PROGBASE.occ"
TBC="$PROGBASE.tbc"
HEX="$PROGBASE.hex"

# Another sanity check
if [ ! -f $OCC ]; then
  echo "Given: $OCC"
  echo "You did not provide an occam file for us to work with."
  exit
fi

AVRDUDE_FLAGS="$TVM_AVRDUDE_CODE_FLAGS -P $UPLOAD_PORT"
AVRDUDE_WRITE_OCCAM="-D -U flash:w:$HEX"

if [ -f $TBC ]; then
  echo "Removing old TBC file..."
  rm $TBC
fi


echo "Compiling..."

# These values come in from arduiniocc-enironment.sh
# I think ISEARCH, being set in the .conf, should do
# the work of finding the platform-specific libraries...
avr-occbuild \
  --search $TVM_INST_ROOT/share/tvm/avr-vtinclude \
  --search $TVM_INST_ROOT/share/tvm/avr-vtlib \
  --search $TVM_INST_ROOT/lib \
  -DF.CPU=$TVM_F_CPU --program $FILENAME

if [ $? -eq 0 ]; then

  if [ -f $HEX ]; then
    echo "Removing old HEX file..."
    rm $HEX
  fi

  if [ $? -eq 0 ]; then
    if [ -f $TBC ]; then
      echo "Converting to .hex..."
      binary-to-ihex $TVM_BYTECODE_ADDR $TBC $HEX
    else
      echo ".tbc file not generated or not found."
      exit
    fi
  fi


  if [ $? -eq 0 ]; then
    if [ -f $HEX ]; then
      echo "Uploading..."
      reset-arduino $UPLOAD_PORT
      avrdude -C $TVM_AVRDUDE_CONF $AVRDUDE_FLAGS $AVRDUDE_WRITE_OCCAM
    else
      echo ".hex file not generated or not found."
      exit
    fi
  fi

  if [ $? -eq 0 ]; then
    echo "Reading..."
    read-arduino $UPLOAD_PORT
  fi
fi
