/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGOCCAMPI
#define SWIG_init    initoccSDL

#define SWIG_name    "occSDL"
#ifdef __cplusplus
extern "C" {
#endif

#include <string.h>
#include <stdlib.h>

typedef int word;


#include <SDL.h>


#include <SDL_main.h>


#include <SDL_types.h>


#include <SDL_video.h>


#include <SDL_keysym.h>


#include <SDL_keyboard.h>


#include <SDL_joystick.h>


#include <SDL_audio.h>


#include <SDL_events.h>


#include <SDL_error.h>


#ifdef __cplusplus
}
#endif
