/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#include "opengl_wrap.h"
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC)
#   if (__SUNPRO_CC <= 0x560)
#     define SWIGTEMPLATEDISAMBIGUATOR template
#   else
#     define SWIGTEMPLATEDISAMBIGUATOR 
#   endif
# else
#   define SWIGTEMPLATEDISAMBIGUATOR 
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

DLLPREFIX void _glClearIndex (word w[])

{
  glClearIndex ((VAL_REAL32(w[0])));
  return;
}


DLLPREFIX void _glClearColor (word w[])

{
  glClearColor ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])), (VAL_REAL32(w[3])));
  return;
}


DLLPREFIX void _glClear (word w[])

{
  glClear ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glIndexMask (word w[])

{
  glIndexMask ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glColorMask (word w[])

{
  glColorMask ((VAL_BYTE(w[0])), (VAL_BYTE(w[1])), (VAL_BYTE(w[2])), (VAL_BYTE(w[3])));
  return;
}


DLLPREFIX void _glAlphaFunc (word w[])

{
  glAlphaFunc ((VAL_INT(w[0])), (VAL_REAL32(w[1])));
  return;
}


DLLPREFIX void _glBlendFunc (word w[])

{
  glBlendFunc ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glLogicOp (word w[])

{
  glLogicOp ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glCullFace (word w[])

{
  glCullFace ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glFrontFace (word w[])

{
  glFrontFace ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glPointSize (word w[])

{
  glPointSize ((VAL_REAL32(w[0])));
  return;
}


DLLPREFIX void _glLineWidth (word w[])

{
  glLineWidth ((VAL_REAL32(w[0])));
  return;
}


DLLPREFIX void _glLineStipple (word w[])

{
  glLineStipple ((VAL_INT(w[0])), (VAL_INT16(w[1])));
  return;
}


DLLPREFIX void _glPolygonMode (word w[])

{
  glPolygonMode ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glPolygonOffset (word w[])

{
  glPolygonOffset ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])));
  return;
}


DLLPREFIX void _glPolygonStipple (word w[])

{
  glPolygonStipple ((BYTE(w[0])));
  return;
}


DLLPREFIX void _glGetPolygonStipple (word w[])

{
  glGetPolygonStipple ((BYTE(w[0])));
  return;
}


DLLPREFIX void _glEdgeFlag (word w[])

{
  glEdgeFlag ((VAL_BYTE(w[0])));
  return;
}


DLLPREFIX void _glEdgeFlagv (word w[])

{
  glEdgeFlagv ((BYTE(w[0])));
  return;
}


DLLPREFIX void _glScissor (word w[])

{
  glScissor ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])));
  return;
}


DLLPREFIX void _glClipPlane (word w[])

{
  glClipPlane ((VAL_INT(w[0])), (REAL64(w[1])));
  return;
}


DLLPREFIX void _glGetClipPlane (word w[])

{
  glGetClipPlane ((VAL_INT(w[0])), (REAL64(w[1])));
  return;
}


DLLPREFIX void _glDrawBuffer (word w[])

{
  glDrawBuffer ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glReadBuffer (word w[])

{
  glReadBuffer ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glEnable (word w[])

{
  glEnable ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glDisable (word w[])

{
  glDisable ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glIsEnabled (word w[])

{
  *(BYTE(w[0])) = glIsEnabled ((VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glEnableClientState (word w[])

{
  glEnableClientState ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glDisableClientState (word w[])

{
  glDisableClientState ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glGetBooleanv (word w[])

{
  glGetBooleanv ((VAL_INT(w[0])), (BYTE(w[1])));
  return;
}


DLLPREFIX void _glGetDoublev (word w[])

{
  glGetDoublev ((VAL_INT(w[0])), (REAL64(w[1])));
  return;
}


DLLPREFIX void _glGetFloatv (word w[])

{
  glGetFloatv ((VAL_INT(w[0])), (REAL32(w[1])));
  return;
}


DLLPREFIX void _glGetIntegerv (word w[])

{
  glGetIntegerv ((VAL_INT(w[0])), (INT(w[1])));
  return;
}


DLLPREFIX void _glPushAttrib (word w[])

{
  glPushAttrib ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glPopAttrib ()

{
  glPopAttrib ();
  return;
}


DLLPREFIX void _glPushClientAttrib (word w[])

{
  glPushClientAttrib ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glPopClientAttrib ()

{
  glPopClientAttrib ();
  return;
}


DLLPREFIX void _glRenderMode (word w[])

{
  *(INT(w[0])) = glRenderMode ((VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glGetError (word w[])

{
  *(INT(w[0])) = glGetError ();
  return;
}


DLLPREFIX void _glGetString (word w[])

{
  *(BYTE(w[0])) = glGetString ((VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glFinish ()

{
  glFinish ();
  return;
}


DLLPREFIX void _glFlush ()

{
  glFlush ();
  return;
}


DLLPREFIX void _glHint (word w[])

{
  glHint ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glClearDepth (word w[])

{
  glClearDepth ((VAL_REAL64(w[0])));
  return;
}


DLLPREFIX void _glDepthFunc (word w[])

{
  glDepthFunc ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glDepthMask (word w[])

{
  glDepthMask ((VAL_BYTE(w[0])));
  return;
}


DLLPREFIX void _glDepthRange (word w[])

{
  glDepthRange ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])));
  return;
}


DLLPREFIX void _glClearAccum (word w[])

{
  glClearAccum ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])), (VAL_REAL32(w[3])));
  return;
}


DLLPREFIX void _glAccum (word w[])

{
  glAccum ((VAL_INT(w[0])), (VAL_REAL32(w[1])));
  return;
}


DLLPREFIX void _glMatrixMode (word w[])

{
  glMatrixMode ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glOrtho (word w[])

{
  glOrtho ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])), (VAL_REAL64(w[4])), (VAL_REAL64(w[5])));
  return;
}


DLLPREFIX void _glFrustum (word w[])

{
  glFrustum ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])), (VAL_REAL64(w[4])), (VAL_REAL64(w[5])));
  return;
}


DLLPREFIX void _glViewport (word w[])

{
  glViewport ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])));
  return;
}


DLLPREFIX void _glPushMatrix ()

{
  glPushMatrix ();
  return;
}


DLLPREFIX void _glPopMatrix ()

{
  glPopMatrix ();
  return;
}


DLLPREFIX void _glLoadIdentity ()

{
  glLoadIdentity ();
  return;
}


DLLPREFIX void _glLoadMatrixd (word w[])

{
  glLoadMatrixd ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glLoadMatrixf (word w[])

{
  glLoadMatrixf ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glMultMatrixd (word w[])

{
  glMultMatrixd ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glMultMatrixf (word w[])

{
  glMultMatrixf ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glRotated (word w[])

{
  glRotated ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])));
  return;
}


DLLPREFIX void _glRotatef (word w[])

{
  glRotatef ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])), (VAL_REAL32(w[3])));
  return;
}


DLLPREFIX void _glScaled (word w[])

{
  glScaled ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])));
  return;
}


DLLPREFIX void _glScalef (word w[])

{
  glScalef ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glTranslated (word w[])

{
  glTranslated ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])));
  return;
}


DLLPREFIX void _glTranslatef (word w[])

{
  glTranslatef ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glIsList (word w[])

{
  *(BYTE(w[0])) = glIsList ((VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glDeleteLists (word w[])

{
  glDeleteLists ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glGenLists (word w[])

{
  *(INT(w[0])) = glGenLists ((VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glNewList (word w[])

{
  glNewList ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glEndList ()

{
  glEndList ();
  return;
}


DLLPREFIX void _glCallList (word w[])

{
  glCallList ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glCallLists (word w[])

{
  glCallLists ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glListBase (word w[])

{
  glListBase ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glBegin (word w[])

{
  glBegin ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glEnd ()

{
  glEnd ();
  return;
}


DLLPREFIX void _glVertex2d (word w[])

{
  glVertex2d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])));
  return;
}


DLLPREFIX void _glVertex2f (word w[])

{
  glVertex2f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])));
  return;
}


DLLPREFIX void _glVertex2i (word w[])

{
  glVertex2i ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glVertex2s (word w[])

{
  glVertex2s ((VAL_INT16(w[0])), (VAL_INT16(w[1])));
  return;
}


DLLPREFIX void _glVertex3d (word w[])

{
  glVertex3d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])));
  return;
}


DLLPREFIX void _glVertex3f (word w[])

{
  glVertex3f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glVertex3i (word w[])

{
  glVertex3i ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glVertex3s (word w[])

{
  glVertex3s ((VAL_INT16(w[0])), (VAL_INT16(w[1])), (VAL_INT16(w[2])));
  return;
}


DLLPREFIX void _glVertex4d (word w[])

{
  glVertex4d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])));
  return;
}


DLLPREFIX void _glVertex4f (word w[])

{
  glVertex4f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])), (VAL_REAL32(w[3])));
  return;
}


DLLPREFIX void _glVertex4i (word w[])

{
  glVertex4i ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])));
  return;
}


DLLPREFIX void _glVertex4s (word w[])

{
  glVertex4s ((VAL_INT16(w[0])), (VAL_INT16(w[1])), (VAL_INT16(w[2])), (VAL_INT16(w[3])));
  return;
}


DLLPREFIX void _glVertex2dv (word w[])

{
  glVertex2dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glVertex2fv (word w[])

{
  glVertex2fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glVertex2iv (word w[])

{
  glVertex2iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glVertex2sv (word w[])

{
  glVertex2sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glVertex3dv (word w[])

{
  glVertex3dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glVertex3fv (word w[])

{
  glVertex3fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glVertex3iv (word w[])

{
  glVertex3iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glVertex3sv (word w[])

{
  glVertex3sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glVertex4dv (word w[])

{
  glVertex4dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glVertex4fv (word w[])

{
  glVertex4fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glVertex4iv (word w[])

{
  glVertex4iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glVertex4sv (word w[])

{
  glVertex4sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glNormal3b (word w[])

{
  glNormal3b ((VAL_BYTE(w[0])), (VAL_BYTE(w[1])), (VAL_BYTE(w[2])));
  return;
}


DLLPREFIX void _glNormal3d (word w[])

{
  glNormal3d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])));
  return;
}


DLLPREFIX void _glNormal3f (word w[])

{
  glNormal3f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glNormal3i (word w[])

{
  glNormal3i ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glNormal3s (word w[])

{
  glNormal3s ((VAL_INT16(w[0])), (VAL_INT16(w[1])), (VAL_INT16(w[2])));
  return;
}


DLLPREFIX void _glNormal3bv (word w[])

{
  glNormal3bv ((BYTE(w[0])));
  return;
}


DLLPREFIX void _glNormal3dv (word w[])

{
  glNormal3dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glNormal3fv (word w[])

{
  glNormal3fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glNormal3iv (word w[])

{
  glNormal3iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glNormal3sv (word w[])

{
  glNormal3sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glIndexd (word w[])

{
  glIndexd ((VAL_REAL64(w[0])));
  return;
}


DLLPREFIX void _glIndexf (word w[])

{
  glIndexf ((VAL_REAL32(w[0])));
  return;
}


DLLPREFIX void _glIndexi (word w[])

{
  glIndexi ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glIndexs (word w[])

{
  glIndexs ((VAL_INT16(w[0])));
  return;
}


DLLPREFIX void _glIndexub (word w[])

{
  glIndexub ((VAL_BYTE(w[0])));
  return;
}


DLLPREFIX void _glIndexdv (word w[])

{
  glIndexdv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glIndexfv (word w[])

{
  glIndexfv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glIndexiv (word w[])

{
  glIndexiv ((INT(w[0])));
  return;
}


DLLPREFIX void _glIndexsv (word w[])

{
  glIndexsv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glIndexubv (word w[])

{
  glIndexubv ((BYTE(w[0])));
  return;
}


DLLPREFIX void _glColor3b (word w[])

{
  glColor3b ((VAL_BYTE(w[0])), (VAL_BYTE(w[1])), (VAL_BYTE(w[2])));
  return;
}


DLLPREFIX void _glColor3d (word w[])

{
  glColor3d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])));
  return;
}


DLLPREFIX void _glColor3f (word w[])

{
  glColor3f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glColor3i (word w[])

{
  glColor3i ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glColor3s (word w[])

{
  glColor3s ((VAL_INT16(w[0])), (VAL_INT16(w[1])), (VAL_INT16(w[2])));
  return;
}


DLLPREFIX void _glColor3ub (word w[])

{
  glColor3ub ((VAL_BYTE(w[0])), (VAL_BYTE(w[1])), (VAL_BYTE(w[2])));
  return;
}


DLLPREFIX void _glColor3ui (word w[])

{
  glColor3ui ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glColor3us (word w[])

{
  glColor3us ((VAL_INT16(w[0])), (VAL_INT16(w[1])), (VAL_INT16(w[2])));
  return;
}


DLLPREFIX void _glColor4b (word w[])

{
  glColor4b ((VAL_BYTE(w[0])), (VAL_BYTE(w[1])), (VAL_BYTE(w[2])), (VAL_BYTE(w[3])));
  return;
}


DLLPREFIX void _glColor4d (word w[])

{
  glColor4d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])));
  return;
}


DLLPREFIX void _glColor4f (word w[])

{
  glColor4f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])), (VAL_REAL32(w[3])));
  return;
}


DLLPREFIX void _glColor4i (word w[])

{
  glColor4i ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])));
  return;
}


DLLPREFIX void _glColor4s (word w[])

{
  glColor4s ((VAL_INT16(w[0])), (VAL_INT16(w[1])), (VAL_INT16(w[2])), (VAL_INT16(w[3])));
  return;
}


DLLPREFIX void _glColor4ub (word w[])

{
  glColor4ub ((VAL_BYTE(w[0])), (VAL_BYTE(w[1])), (VAL_BYTE(w[2])), (VAL_BYTE(w[3])));
  return;
}


DLLPREFIX void _glColor4ui (word w[])

{
  glColor4ui ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])));
  return;
}


DLLPREFIX void _glColor4us (word w[])

{
  glColor4us ((VAL_INT16(w[0])), (VAL_INT16(w[1])), (VAL_INT16(w[2])), (VAL_INT16(w[3])));
  return;
}


DLLPREFIX void _glColor3bv (word w[])

{
  glColor3bv ((BYTE(w[0])));
  return;
}


DLLPREFIX void _glColor3dv (word w[])

{
  glColor3dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glColor3fv (word w[])

{
  glColor3fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glColor3iv (word w[])

{
  glColor3iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glColor3sv (word w[])

{
  glColor3sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glColor3ubv (word w[])

{
  glColor3ubv ((BYTE(w[0])));
  return;
}


DLLPREFIX void _glColor3uiv (word w[])

{
  glColor3uiv ((INT(w[0])));
  return;
}


DLLPREFIX void _glColor3usv (word w[])

{
  glColor3usv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glColor4bv (word w[])

{
  glColor4bv ((BYTE(w[0])));
  return;
}


DLLPREFIX void _glColor4dv (word w[])

{
  glColor4dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glColor4fv (word w[])

{
  glColor4fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glColor4iv (word w[])

{
  glColor4iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glColor4sv (word w[])

{
  glColor4sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glColor4ubv (word w[])

{
  glColor4ubv ((BYTE(w[0])));
  return;
}


DLLPREFIX void _glColor4uiv (word w[])

{
  glColor4uiv ((INT(w[0])));
  return;
}


DLLPREFIX void _glColor4usv (word w[])

{
  glColor4usv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glTexCoord1d (word w[])

{
  glTexCoord1d ((VAL_REAL64(w[0])));
  return;
}


DLLPREFIX void _glTexCoord1f (word w[])

{
  glTexCoord1f ((VAL_REAL32(w[0])));
  return;
}


DLLPREFIX void _glTexCoord1i (word w[])

{
  glTexCoord1i ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glTexCoord1s (word w[])

{
  glTexCoord1s ((VAL_INT16(w[0])));
  return;
}


DLLPREFIX void _glTexCoord2d (word w[])

{
  glTexCoord2d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])));
  return;
}


DLLPREFIX void _glTexCoord2f (word w[])

{
  glTexCoord2f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])));
  return;
}


DLLPREFIX void _glTexCoord2i (word w[])

{
  glTexCoord2i ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glTexCoord2s (word w[])

{
  glTexCoord2s ((VAL_INT16(w[0])), (VAL_INT16(w[1])));
  return;
}


DLLPREFIX void _glTexCoord3d (word w[])

{
  glTexCoord3d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])));
  return;
}


DLLPREFIX void _glTexCoord3f (word w[])

{
  glTexCoord3f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glTexCoord3i (word w[])

{
  glTexCoord3i ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glTexCoord3s (word w[])

{
  glTexCoord3s ((VAL_INT16(w[0])), (VAL_INT16(w[1])), (VAL_INT16(w[2])));
  return;
}


DLLPREFIX void _glTexCoord4d (word w[])

{
  glTexCoord4d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])));
  return;
}


DLLPREFIX void _glTexCoord4f (word w[])

{
  glTexCoord4f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])), (VAL_REAL32(w[3])));
  return;
}


DLLPREFIX void _glTexCoord4i (word w[])

{
  glTexCoord4i ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])));
  return;
}


DLLPREFIX void _glTexCoord4s (word w[])

{
  glTexCoord4s ((VAL_INT16(w[0])), (VAL_INT16(w[1])), (VAL_INT16(w[2])), (VAL_INT16(w[3])));
  return;
}


DLLPREFIX void _glTexCoord1dv (word w[])

{
  glTexCoord1dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glTexCoord1fv (word w[])

{
  glTexCoord1fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glTexCoord1iv (word w[])

{
  glTexCoord1iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glTexCoord1sv (word w[])

{
  glTexCoord1sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glTexCoord2dv (word w[])

{
  glTexCoord2dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glTexCoord2fv (word w[])

{
  glTexCoord2fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glTexCoord2iv (word w[])

{
  glTexCoord2iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glTexCoord2sv (word w[])

{
  glTexCoord2sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glTexCoord3dv (word w[])

{
  glTexCoord3dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glTexCoord3fv (word w[])

{
  glTexCoord3fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glTexCoord3iv (word w[])

{
  glTexCoord3iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glTexCoord3sv (word w[])

{
  glTexCoord3sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glTexCoord4dv (word w[])

{
  glTexCoord4dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glTexCoord4fv (word w[])

{
  glTexCoord4fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glTexCoord4iv (word w[])

{
  glTexCoord4iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glTexCoord4sv (word w[])

{
  glTexCoord4sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glRasterPos2d (word w[])

{
  glRasterPos2d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])));
  return;
}


DLLPREFIX void _glRasterPos2f (word w[])

{
  glRasterPos2f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])));
  return;
}


DLLPREFIX void _glRasterPos2i (word w[])

{
  glRasterPos2i ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glRasterPos2s (word w[])

{
  glRasterPos2s ((VAL_INT16(w[0])), (VAL_INT16(w[1])));
  return;
}


DLLPREFIX void _glRasterPos3d (word w[])

{
  glRasterPos3d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])));
  return;
}


DLLPREFIX void _glRasterPos3f (word w[])

{
  glRasterPos3f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glRasterPos3i (word w[])

{
  glRasterPos3i ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glRasterPos3s (word w[])

{
  glRasterPos3s ((VAL_INT16(w[0])), (VAL_INT16(w[1])), (VAL_INT16(w[2])));
  return;
}


DLLPREFIX void _glRasterPos4d (word w[])

{
  glRasterPos4d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])));
  return;
}


DLLPREFIX void _glRasterPos4f (word w[])

{
  glRasterPos4f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])), (VAL_REAL32(w[3])));
  return;
}


DLLPREFIX void _glRasterPos4i (word w[])

{
  glRasterPos4i ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])));
  return;
}


DLLPREFIX void _glRasterPos4s (word w[])

{
  glRasterPos4s ((VAL_INT16(w[0])), (VAL_INT16(w[1])), (VAL_INT16(w[2])), (VAL_INT16(w[3])));
  return;
}


DLLPREFIX void _glRasterPos2dv (word w[])

{
  glRasterPos2dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glRasterPos2fv (word w[])

{
  glRasterPos2fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glRasterPos2iv (word w[])

{
  glRasterPos2iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glRasterPos2sv (word w[])

{
  glRasterPos2sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glRasterPos3dv (word w[])

{
  glRasterPos3dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glRasterPos3fv (word w[])

{
  glRasterPos3fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glRasterPos3iv (word w[])

{
  glRasterPos3iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glRasterPos3sv (word w[])

{
  glRasterPos3sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glRasterPos4dv (word w[])

{
  glRasterPos4dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glRasterPos4fv (word w[])

{
  glRasterPos4fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glRasterPos4iv (word w[])

{
  glRasterPos4iv ((INT(w[0])));
  return;
}


DLLPREFIX void _glRasterPos4sv (word w[])

{
  glRasterPos4sv ((INT16(w[0])));
  return;
}


DLLPREFIX void _glRectd (word w[])

{
  glRectd ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])));
  return;
}


DLLPREFIX void _glRectf (word w[])

{
  glRectf ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])), (VAL_REAL32(w[3])));
  return;
}


DLLPREFIX void _glRecti (word w[])

{
  glRecti ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])));
  return;
}


DLLPREFIX void _glRects (word w[])

{
  glRects ((VAL_INT16(w[0])), (VAL_INT16(w[1])), (VAL_INT16(w[2])), (VAL_INT16(w[3])));
  return;
}


DLLPREFIX void _glRectdv (word w[])

{
  glRectdv ((REAL64(w[0])), (REAL64(w[2])));
  return;
}


DLLPREFIX void _glRectfv (word w[])

{
  glRectfv ((REAL32(w[0])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glRectiv (word w[])

{
  glRectiv ((INT(w[0])), (INT(w[2])));
  return;
}


DLLPREFIX void _glRectsv (word w[])

{
  glRectsv ((INT16(w[0])), (INT16(w[2])));
  return;
}


DLLPREFIX void _glVertexPointer (word w[])

{
  glVertexPointer ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (INT(w[3])));
  return;
}


DLLPREFIX void _glNormalPointer (word w[])

{
  glNormalPointer ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glColorPointer (word w[])

{
  glColorPointer ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (INT(w[3])));
  return;
}


DLLPREFIX void _glIndexPointer (word w[])

{
  glIndexPointer ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glTexCoordPointer (word w[])

{
  glTexCoordPointer ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (INT(w[3])));
  return;
}


DLLPREFIX void _glEdgeFlagPointer (word w[])

{
  glEdgeFlagPointer ((VAL_INT(w[0])), (INT(w[1])));
  return;
}


DLLPREFIX void _glGetPointerv (word w[])

{
  glGetPointerv ((VAL_INT(w[0])), (INT(w[1])));
  return;
}


DLLPREFIX void _glArrayElement (word w[])

{
  glArrayElement ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glDrawArrays (word w[])

{
  glDrawArrays ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glDrawElements (word w[])

{
  glDrawElements ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (INT(w[3])));
  return;
}


DLLPREFIX void _glInterleavedArrays (word w[])

{
  glInterleavedArrays ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glShadeModel (word w[])

{
  glShadeModel ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glLightf (word w[])

{
  glLightf ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glLighti (word w[])

{
  glLighti ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glLightfv (word w[])

{
  glLightfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glLightiv (word w[])

{
  glLightiv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glGetLightfv (word w[])

{
  glGetLightfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glGetLightiv (word w[])

{
  glGetLightiv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glLightModelf (word w[])

{
  glLightModelf ((VAL_INT(w[0])), (VAL_REAL32(w[1])));
  return;
}


DLLPREFIX void _glLightModeli (word w[])

{
  glLightModeli ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glLightModelfv (word w[])

{
  glLightModelfv ((VAL_INT(w[0])), (REAL32(w[1])));
  return;
}


DLLPREFIX void _glLightModeliv (word w[])

{
  glLightModeliv ((VAL_INT(w[0])), (INT(w[1])));
  return;
}


DLLPREFIX void _glMaterialf (word w[])

{
  glMaterialf ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glMateriali (word w[])

{
  glMateriali ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glMaterialfv (word w[])

{
  glMaterialfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glMaterialiv (word w[])

{
  glMaterialiv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glGetMaterialfv (word w[])

{
  glGetMaterialfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glGetMaterialiv (word w[])

{
  glGetMaterialiv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glColorMaterial (word w[])

{
  glColorMaterial ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glPixelZoom (word w[])

{
  glPixelZoom ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])));
  return;
}


DLLPREFIX void _glPixelStoref (word w[])

{
  glPixelStoref ((VAL_INT(w[0])), (VAL_REAL32(w[1])));
  return;
}


DLLPREFIX void _glPixelStorei (word w[])

{
  glPixelStorei ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glPixelTransferf (word w[])

{
  glPixelTransferf ((VAL_INT(w[0])), (VAL_REAL32(w[1])));
  return;
}


DLLPREFIX void _glPixelTransferi (word w[])

{
  glPixelTransferi ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glPixelMapfv (word w[])

{
  glPixelMapfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glPixelMapuiv (word w[])

{
  glPixelMapuiv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glPixelMapusv (word w[])

{
  glPixelMapusv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT16(w[2])));
  return;
}


DLLPREFIX void _glGetPixelMapfv (word w[])

{
  glGetPixelMapfv ((VAL_INT(w[0])), (REAL32(w[1])));
  return;
}


DLLPREFIX void _glGetPixelMapuiv (word w[])

{
  glGetPixelMapuiv ((VAL_INT(w[0])), (INT(w[1])));
  return;
}


DLLPREFIX void _glGetPixelMapusv (word w[])

{
  glGetPixelMapusv ((VAL_INT(w[0])), (INT16(w[1])));
  return;
}


DLLPREFIX void _glBitmap (word w[])

{
  glBitmap ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_REAL32(w[2])), (VAL_REAL32(w[3])), (VAL_REAL32(w[4])), (VAL_REAL32(w[5])), (BYTE(w[6])));
  return;
}


DLLPREFIX void _glReadPixels (word w[])

{
  glReadPixels ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (VAL_INT(w[5])), (INT(w[6])));
  return;
}


DLLPREFIX void _glDrawPixels (word w[])

{
  glDrawPixels ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (INT(w[4])));
  return;
}


DLLPREFIX void _glCopyPixels (word w[])

{
  glCopyPixels ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])));
  return;
}


DLLPREFIX void _glStencilFunc (word w[])

{
  glStencilFunc ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glStencilMask (word w[])

{
  glStencilMask ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glStencilOp (word w[])

{
  glStencilOp ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glClearStencil (word w[])

{
  glClearStencil ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glTexGend (word w[])

{
  glTexGend ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_REAL64(w[2])));
  return;
}


DLLPREFIX void _glTexGenf (word w[])

{
  glTexGenf ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glTexGeni (word w[])

{
  glTexGeni ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glTexGendv (word w[])

{
  glTexGendv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL64(w[2])));
  return;
}


DLLPREFIX void _glTexGenfv (word w[])

{
  glTexGenfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glTexGeniv (word w[])

{
  glTexGeniv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glGetTexGendv (word w[])

{
  glGetTexGendv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL64(w[2])));
  return;
}


DLLPREFIX void _glGetTexGenfv (word w[])

{
  glGetTexGenfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glGetTexGeniv (word w[])

{
  glGetTexGeniv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glTexEnvf (word w[])

{
  glTexEnvf ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glTexEnvi (word w[])

{
  glTexEnvi ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glTexEnvfv (word w[])

{
  glTexEnvfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glTexEnviv (word w[])

{
  glTexEnviv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glGetTexEnvfv (word w[])

{
  glGetTexEnvfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glGetTexEnviv (word w[])

{
  glGetTexEnviv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glTexParameterf (word w[])

{
  glTexParameterf ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glTexParameteri (word w[])

{
  glTexParameteri ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glTexParameterfv (word w[])

{
  glTexParameterfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glTexParameteriv (word w[])

{
  glTexParameteriv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glGetTexParameterfv (word w[])

{
  glGetTexParameterfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glGetTexParameteriv (word w[])

{
  glGetTexParameteriv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glGetTexLevelParameterfv (word w[])

{
  glGetTexLevelParameterfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (REAL32(w[3])));
  return;
}


DLLPREFIX void _glGetTexLevelParameteriv (word w[])

{
  glGetTexLevelParameteriv ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (INT(w[3])));
  return;
}


DLLPREFIX void _glTexImage1D (word w[])

{
  glTexImage1D ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (VAL_INT(w[5])), (VAL_INT(w[6])), (INT(w[7])));
  return;
}


DLLPREFIX void _glTexImage2D (word w[])

{
  glTexImage2D ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (VAL_INT(w[5])), (VAL_INT(w[6])), (VAL_INT(w[7])), (INT(w[8])));
  return;
}


DLLPREFIX void _glGetTexImage (word w[])

{
  glGetTexImage ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (INT(w[4])));
  return;
}


DLLPREFIX void _glGenTextures (word w[])

{
  glGenTextures ((VAL_INT(w[0])), (INT(w[1])));
  return;
}


DLLPREFIX void _glDeleteTextures (word w[])

{
  glDeleteTextures ((VAL_INT(w[0])), (INT(w[1])));
  return;
}


DLLPREFIX void _glBindTexture (word w[])

{
  glBindTexture ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glPrioritizeTextures (word w[])

{
  glPrioritizeTextures ((VAL_INT(w[0])), (INT(w[1])), (REAL32(w[3])));
  return;
}


DLLPREFIX void _glAreTexturesResident (word w[])

{
  *(BYTE(w[0])) = glAreTexturesResident ((VAL_INT(w[1])), (INT(w[2])), (BYTE(w[4])));
  return;
}


DLLPREFIX void _glIsTexture (word w[])

{
  *(BYTE(w[0])) = glIsTexture ((VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glTexSubImage1D (word w[])

{
  glTexSubImage1D ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (VAL_INT(w[5])), (INT(w[6])));
  return;
}


DLLPREFIX void _glTexSubImage2D (word w[])

{
  glTexSubImage2D ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (VAL_INT(w[5])), (VAL_INT(w[6])), (VAL_INT(w[7])), (INT(w[8])));
  return;
}


DLLPREFIX void _glCopyTexImage1D (word w[])

{
  glCopyTexImage1D ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (VAL_INT(w[5])), (VAL_INT(w[6])));
  return;
}


DLLPREFIX void _glCopyTexImage2D (word w[])

{
  glCopyTexImage2D ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (VAL_INT(w[5])), (VAL_INT(w[6])), (VAL_INT(w[7])));
  return;
}


DLLPREFIX void _glCopyTexSubImage1D (word w[])

{
  glCopyTexSubImage1D ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (VAL_INT(w[5])));
  return;
}


DLLPREFIX void _glCopyTexSubImage2D (word w[])

{
  glCopyTexSubImage2D ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (VAL_INT(w[5])), (VAL_INT(w[6])), (VAL_INT(w[7])));
  return;
}


DLLPREFIX void _glMap1d (word w[])

{
  glMap1d ((VAL_INT(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (REAL64(w[5])));
  return;
}


DLLPREFIX void _glMap1f (word w[])

{
  glMap1f ((VAL_INT(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (REAL32(w[5])));
  return;
}


DLLPREFIX void _glMap2d (word w[])

{
  glMap2d ((VAL_INT(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (VAL_REAL64(w[5])), (VAL_REAL64(w[6])), (VAL_INT(w[7])), (VAL_INT(w[8])), (REAL64(w[9])));
  return;
}


DLLPREFIX void _glMap2f (word w[])

{
  glMap2f ((VAL_INT(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (VAL_REAL32(w[5])), (VAL_REAL32(w[6])), (VAL_INT(w[7])), (VAL_INT(w[8])), (REAL32(w[9])));
  return;
}


DLLPREFIX void _glGetMapdv (word w[])

{
  glGetMapdv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL64(w[2])));
  return;
}


DLLPREFIX void _glGetMapfv (word w[])

{
  glGetMapfv ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glGetMapiv (word w[])

{
  glGetMapiv ((VAL_INT(w[0])), (VAL_INT(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _glEvalCoord1d (word w[])

{
  glEvalCoord1d ((VAL_REAL64(w[0])));
  return;
}


DLLPREFIX void _glEvalCoord1f (word w[])

{
  glEvalCoord1f ((VAL_REAL32(w[0])));
  return;
}


DLLPREFIX void _glEvalCoord1dv (word w[])

{
  glEvalCoord1dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glEvalCoord1fv (word w[])

{
  glEvalCoord1fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glEvalCoord2d (word w[])

{
  glEvalCoord2d ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])));
  return;
}


DLLPREFIX void _glEvalCoord2f (word w[])

{
  glEvalCoord2f ((VAL_REAL32(w[0])), (VAL_REAL32(w[1])));
  return;
}


DLLPREFIX void _glEvalCoord2dv (word w[])

{
  glEvalCoord2dv ((REAL64(w[0])));
  return;
}


DLLPREFIX void _glEvalCoord2fv (word w[])

{
  glEvalCoord2fv ((REAL32(w[0])));
  return;
}


DLLPREFIX void _glMapGrid1d (word w[])

{
  glMapGrid1d ((VAL_INT(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])));
  return;
}


DLLPREFIX void _glMapGrid1f (word w[])

{
  glMapGrid1f ((VAL_INT(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _glMapGrid2d (word w[])

{
  glMapGrid2d ((VAL_INT(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_INT(w[3])), (VAL_REAL64(w[4])), (VAL_REAL64(w[5])));
  return;
}


DLLPREFIX void _glMapGrid2f (word w[])

{
  glMapGrid2f ((VAL_INT(w[0])), (VAL_REAL32(w[1])), (VAL_REAL32(w[2])), (VAL_INT(w[3])), (VAL_REAL32(w[4])), (VAL_REAL32(w[5])));
  return;
}


DLLPREFIX void _glEvalPoint1 (word w[])

{
  glEvalPoint1 ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glEvalPoint2 (word w[])

{
  glEvalPoint2 ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glEvalMesh1 (word w[])

{
  glEvalMesh1 ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])));
  return;
}


DLLPREFIX void _glEvalMesh2 (word w[])

{
  glEvalMesh2 ((VAL_INT(w[0])), (VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])));
  return;
}


DLLPREFIX void _glFogf (word w[])

{
  glFogf ((VAL_INT(w[0])), (VAL_REAL32(w[1])));
  return;
}


DLLPREFIX void _glFogi (word w[])

{
  glFogi ((VAL_INT(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _glFogfv (word w[])

{
  glFogfv ((VAL_INT(w[0])), (REAL32(w[1])));
  return;
}


DLLPREFIX void _glFogiv (word w[])

{
  glFogiv ((VAL_INT(w[0])), (INT(w[1])));
  return;
}


DLLPREFIX void _glFeedbackBuffer (word w[])

{
  glFeedbackBuffer ((VAL_INT(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _glPassThrough (word w[])

{
  glPassThrough ((VAL_REAL32(w[0])));
  return;
}


DLLPREFIX void _glSelectBuffer (word w[])

{
  glSelectBuffer ((VAL_INT(w[0])), (INT(w[1])));
  return;
}


DLLPREFIX void _glInitNames ()

{
  glInitNames ();
  return;
}


DLLPREFIX void _glLoadName (word w[])

{
  glLoadName ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glPushName (word w[])

{
  glPushName ((VAL_INT(w[0])));
  return;
}


DLLPREFIX void _glPopName ()

{
  glPopName ();
  return;
}


DLLPREFIX void _gluBeginCurve (word w[])

{
  gluBeginCurve (((GLUnurbs*)(w[0])));
  return;
}


DLLPREFIX void _gluBeginPolygon (word w[])

{
  gluBeginPolygon (((GLUtesselator*)(w[0])));
  return;
}


DLLPREFIX void _gluBeginSurface (word w[])

{
  gluBeginSurface (((GLUnurbs*)(w[0])));
  return;
}


DLLPREFIX void _gluBeginTrim (word w[])

{
  gluBeginTrim (((GLUnurbs*)(w[0])));
  return;
}


DLLPREFIX void _gluCylinder (word w[])

{
  gluCylinder (((GLUquadric*)(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])), (VAL_INT(w[4])), (VAL_INT(w[5])));
  return;
}


DLLPREFIX void _gluDeleteNurbsRenderer (word w[])

{
  gluDeleteNurbsRenderer (((GLUnurbs*)(w[0])));
  return;
}


DLLPREFIX void _gluDeleteQuadric (word w[])

{
  gluDeleteQuadric (((GLUquadric*)(w[0])));
  return;
}


DLLPREFIX void _gluDeleteTess (word w[])

{
  gluDeleteTess (((GLUtesselator*)(w[0])));
  return;
}


DLLPREFIX void _gluDisk (word w[])

{
  gluDisk (((GLUquadric*)(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])));
  return;
}


DLLPREFIX void _gluEndCurve (word w[])

{
  gluEndCurve (((GLUnurbs*)(w[0])));
  return;
}


DLLPREFIX void _gluEndPolygon (word w[])

{
  gluEndPolygon (((GLUtesselator*)(w[0])));
  return;
}


DLLPREFIX void _gluEndSurface (word w[])

{
  gluEndSurface (((GLUnurbs*)(w[0])));
  return;
}


DLLPREFIX void _gluEndTrim (word w[])

{
  gluEndTrim (((GLUnurbs*)(w[0])));
  return;
}


DLLPREFIX void _gluErrorString (word w[])

{
  *(BYTE(w[0])) = gluErrorString ((VAL_INT(w[1])));
  return;
}


DLLPREFIX void _gluGetNurbsProperty (word w[])

{
  gluGetNurbsProperty (((GLUnurbs*)(w[0])), (VAL_INT(w[1])), (REAL32(w[2])));
  return;
}


DLLPREFIX void _gluGetString (word w[])

{
  *(BYTE(w[0])) = gluGetString ((VAL_INT(w[1])));
  return;
}


DLLPREFIX void _gluGetTessProperty (word w[])

{
  gluGetTessProperty (((GLUtesselator*)(w[0])), (VAL_INT(w[1])), (REAL64(w[2])));
  return;
}


DLLPREFIX void _gluLoadSamplingMatrices (word w[])

{
  gluLoadSamplingMatrices (((GLUnurbs*)(w[0])), (REAL32(w[1])), (REAL32(w[2])), (INT(w[3])));
  return;
}


DLLPREFIX void _gluLookAt (word w[])

{
  gluLookAt ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])), (VAL_REAL64(w[4])), (VAL_REAL64(w[5])), (VAL_REAL64(w[6])), (VAL_REAL64(w[7])), (VAL_REAL64(w[8])));
  return;
}


DLLPREFIX void _gluNewNurbsRenderer (word w[])

{
  (w[0]) = gluNewNurbsRenderer ();
  return;
}


DLLPREFIX void _gluNewQuadric (word w[])

{
  (w[0]) = gluNewQuadric ();
  return;
}


DLLPREFIX void _gluNewTess (word w[])

{
  (w[0]) = gluNewTess ();
  return;
}


DLLPREFIX void _gluNextContour (word w[])

{
  gluNextContour (((GLUtesselator*)(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _gluNurbsCurve (word w[])

{
  gluNurbsCurve (((GLUnurbs*)(w[0])), (VAL_INT(w[1])), (REAL32(w[2])), (VAL_INT(w[3])), (REAL32(w[4])), (VAL_INT(w[5])), (VAL_INT(w[6])));
  return;
}


DLLPREFIX void _gluNurbsProperty (word w[])

{
  gluNurbsProperty (((GLUnurbs*)(w[0])), (VAL_INT(w[1])), (VAL_REAL32(w[2])));
  return;
}


DLLPREFIX void _gluNurbsSurface (word w[])

{
  gluNurbsSurface (((GLUnurbs*)(w[0])), (VAL_INT(w[1])), (REAL32(w[2])), (VAL_INT(w[3])), (REAL32(w[4])), (VAL_INT(w[5])), (VAL_INT(w[6])), (REAL32(w[7])), (VAL_INT(w[8])), (VAL_INT(w[9])), (VAL_INT(w[10])));
  return;
}


DLLPREFIX void _gluOrtho2D (word w[])

{
  gluOrtho2D ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])));
  return;
}


DLLPREFIX void _gluPartialDisk (word w[])

{
  gluPartialDisk (((GLUquadric*)(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (VAL_REAL64(w[5])), (VAL_REAL64(w[6])));
  return;
}


DLLPREFIX void _gluPerspective (word w[])

{
  gluPerspective ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])));
  return;
}


DLLPREFIX void _gluPickMatrix (word w[])

{
  gluPickMatrix ((VAL_REAL64(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])), (INT(w[4])));
  return;
}


DLLPREFIX void _gluProject (word w[])

{
  *(INT(w[0])) = gluProject ((VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])), (REAL64(w[4])), (REAL64(w[5])), (INT(w[6])), (REAL64(w[7])), (REAL64(w[8])), (REAL64(w[9])));
  return;
}


DLLPREFIX void _gluPwlCurve (word w[])

{
  gluPwlCurve (((GLUnurbs*)(w[0])), (VAL_INT(w[1])), (REAL32(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])));
  return;
}


DLLPREFIX void _gluQuadricDrawStyle (word w[])

{
  gluQuadricDrawStyle (((GLUquadric*)(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _gluQuadricNormals (word w[])

{
  gluQuadricNormals (((GLUquadric*)(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _gluQuadricOrientation (word w[])

{
  gluQuadricOrientation (((GLUquadric*)(w[0])), (VAL_INT(w[1])));
  return;
}


DLLPREFIX void _gluQuadricTexture (word w[])

{
  gluQuadricTexture (((GLUquadric*)(w[0])), (VAL_BYTE(w[1])));
  return;
}


DLLPREFIX void _gluScaleImage (word w[])

{
  *(INT(w[0])) = gluScaleImage ((VAL_INT(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])), (VAL_INT(w[4])), (INT(w[5])), (VAL_INT(w[6])), (VAL_INT(w[7])), (VAL_INT(w[8])), (INT(w[9])));
  return;
}


DLLPREFIX void _gluSphere (word w[])

{
  gluSphere (((GLUquadric*)(w[0])), (VAL_REAL64(w[1])), (VAL_INT(w[2])), (VAL_INT(w[3])));
  return;
}


DLLPREFIX void _gluTessBeginContour (word w[])

{
  gluTessBeginContour (((GLUtesselator*)(w[0])));
  return;
}


DLLPREFIX void _gluTessBeginPolygon (word w[])

{
  gluTessBeginPolygon (((GLUtesselator*)(w[0])), (INT(w[1])));
  return;
}


DLLPREFIX void _gluTessEndContour (word w[])

{
  gluTessEndContour (((GLUtesselator*)(w[0])));
  return;
}


DLLPREFIX void _gluTessEndPolygon (word w[])

{
  gluTessEndPolygon (((GLUtesselator*)(w[0])));
  return;
}


DLLPREFIX void _gluTessNormal (word w[])

{
  gluTessNormal (((GLUtesselator*)(w[0])), (VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])));
  return;
}


DLLPREFIX void _gluTessProperty (word w[])

{
  gluTessProperty (((GLUtesselator*)(w[0])), (VAL_INT(w[1])), (VAL_REAL64(w[2])));
  return;
}


DLLPREFIX void _gluTessVertex (word w[])

{
  gluTessVertex (((GLUtesselator*)(w[0])), (REAL64(w[1])), (INT(w[2])));
  return;
}


DLLPREFIX void _gluUnProject (word w[])

{
  *(INT(w[0])) = gluUnProject ((VAL_REAL64(w[1])), (VAL_REAL64(w[2])), (VAL_REAL64(w[3])), (REAL64(w[4])), (REAL64(w[5])), (INT(w[6])), (REAL64(w[7])), (REAL64(w[8])), (REAL64(w[9])));
  return;
}


