/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin */

#ifndef _Included_org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin
#define _Included_org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin_init
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin_unload
  (JNIEnv *, jobject);

/*
 * Class:     org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin
 * Method:    performUpdateCheckWithUI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin_performUpdateCheckWithUI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
