/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin */

#ifndef _Included_org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin
#define _Included_org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin
 * Method:    win_sparkle_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_transterpreter_jeditwinsparkleplugin_JEditWinSparklePlugin_win_1sparkle_1init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
