/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_transterpreter_occPlug_hosts_Native */

#ifndef _Included_org_transterpreter_occPlug_hosts_Native
#define _Included_org_transterpreter_occPlug_hosts_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_transterpreter_occPlug_hosts_Native
 * Method:    getSerialPorts
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_transterpreter_occPlug_hosts_Native_getSerialPorts
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
