/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_transterpreter_occPlug_hosts_Native */

#ifndef _Included_org_transterpreter_occPlug_hosts_Native
#define _Included_org_transterpreter_occPlug_hosts_Native
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: kUSBVendorID */
/* Inaccessible static: kUSBProductID */
/* Inaccessible static: kUSBProductString */
/* Inaccessible static: kUSBVendorString */
/* Inaccessible static: kUSBSerialNumberString */
/*
 * Class:     org_transterpreter_occPlug_hosts_Native
 * Method:    _getSerialPorts
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_transterpreter_occPlug_hosts_Native__1getSerialPorts
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
