 --
 --  This library is free software; you can redistribute it and/or
 --  modify it under the terms of the GNU Lesser General Public
 --  License as published by the Free Software Foundation; either
 --  version 2.1 of the License, or (at your option) any later version.
 --
 --  This library is distributed in the hope that it will be useful,
 --  but WITHOUT ANY WARRANTY; without even the implied warranty of
 --  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 --  Lesser General Public License for more details.
 --
 --  You should have received a copy of the GNU Lesser General Public
 --  License along with this library; if not, write to the Free 
 --  Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 --  Boston, MA  02110-1301  USA
 -- 
 --  **********************************************************************

 --  This module contains the FFI to enable calls to servos.c, the
 --  servo driver for the Arduino.

#PRAGMA EXTERNAL "PROC BX.addServo( VAL INT pin ) = 0"

INLINE PROC addServo( VAL INT pin )
  BX.addServo( pin )
:

#PRAGMA EXTERNAL "PROC BX.setServoPositionInDegrees( VAL INT pin, VAL INT degrees ) = 0"

INLINE PROC setServoPositionInDegrees( VAL INT pin, VAL INT degrees )
  BX.setServoPositionInDegrees( pin, degrees )
:

