/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGOCCAMPI
#define SWIG_init    initoccplayer

#define SWIG_name    "occplayer"
#ifdef __cplusplus
extern "C" {
#endif

#include <string.h>
#include <stdlib.h>

typedef int word;


#include <stdint.h>		// Use the C99 official header


#include <libplayercore/player.h>
#include <libplayerc/playerc.h>


#ifdef __cplusplus
}
#endif
