--
--	Inmos Libraries
--	Copyright (C) 1988, 1989, 1990, 1991, 1993  Inmos Limited
--
--	This library is free software; you can redistribute it and/or
--	modify it under the terms of the GNU Lesser General Public
--	License as published by the Free Software Foundation; either
--	version 2 of the License, or (at your option) any later version.
--
--	This library is distributed in the hope that it will be useful,
--	but WITHOUT ANY WARRANTY; without even the implied warranty of
--	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
--	Lesser General Public License for more details.
--
--	You should have received a copy of the GNU Lesser General Public
--	License along with this library; if not, write to the Free Software
--	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
--

VAL Unix.NULL IS 0(INT32):
VAL Unix.ACCESS.DENIED IS -1:
VAL Unix.INVALID.HANDLE IS -2:
VAL Unix.BUFFER.OVERFLOW IS -3:

VAL sph.Alpha IS 130(BYTE):
VAL spo.OSF1 IS 130(BYTE):
VAL spo.linux IS 8(BYTE):

VAL needs.endian.swap IS FALSE:

