#!/usr/bin/env python
#
#	Harness for Performance Regression Testing in occam-pi
#	Copyright (C) 2009  Carl Ritson <cgr@kent.ac.uk>
#
#	This program is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; either version 2 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program; if not, write to the Free Software
#	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

import sys, re, urllib

def warn(*s):
	print >>sys.stderr, "buildbot-scrap: " + "".join(map(str, s))

def die(*s):
	warn(*s)
	sys.exit(1)

def main(args):
	if args == []:
		die("No URLs to scrap")

	build_re = re.compile(r'.*<li>.*rev=\[(.*?)\].*\#(\d+)</a>.*: build successful</li>')
	for url in args:
		h = urllib.urlopen(url)
		lines = h.readlines()
		h.close()
		print url
		for line in lines:
			m = build_re.match(line)
			if m is not None:
				(rev, build) = m.group(1, 2)
				print "\t", rev, build

if __name__ == "__main__":
	main(sys.argv[1:])
