CREATE TABLE result (
	result_id	INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	host 		VARCHAR (128) NOT NULL,
	rev		INT UNSIGNED NOT NULL,
	start 		INT UNSIGNED NOT NULL DEFAULT 0,
	name		VARCHAR (64) NOT NULL,
	type		VARCHAR (64) NOT NULL,
	cpus		INT UNSIGNED NOT NULL,
	avg		DOUBLE PRECISION NOT NULL,

	PRIMARY KEY (result_id),

	INDEX (host),
	INDEX (rev),
	INDEX (name)
);
