--
--	Copyright (C) 2009-2010   Christian Jacobsen
--      Copyright (C) 2009-2010   Matt Jadud
--      Copyright (C)      2010   Michael Andrew Pirrone-Brusse
--      Copyright (C) 2009-2010   Adam Sampson
--
--	This library is free software; you can redistribute it and/or
--	modify it under the terms of the GNU Lesser General Public
--	License as published by the Free Software Foundation; either
--	version 2 of the License, or (at your option) any later version.
--
--	This library is distributed in the hope that it will be useful,
--	but WITHOUT ANY WARRANTY; without even the implied warranty of
--	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
--	Lesser General Public License for more details.
--
--      You should have received a copy of the GNU General Public License
--      along with this program.  If not, see <http://www.gnu.org/licenses/>.
--

--WARNING: Do we need this anymore? It's just one function that I don't think
--  even works anymore...

-- This is a module of deprecated code. The kind of cruft we'd like to keep
-- as a reference, but should not actually be used anywhere.

-- Mostly created so that occamdoc doesn't catch depricated PROCs.

--{{{ DEPRECATED FROM PLUMBING
#IF FALSE
-- While this is a nice interrupt-driven approach to ADC,
-- it is not parallel-safe. Because we deschedule when doing a reading,
-- someone else can come in and start another. I have replaced this 
-- with a busywait version until I can come up with a better solution.
--
-- The busywait obviously blocks our runtime until a reading finishes.
-- However, it eliminates the critical section.
PROC adc (VAL INT pin, CHAN SIGNAL req?, CHAN INT val!)
  PLACED [MAX.PORT]BYTE ports 0:
  INT16 result:   
  SEQ
    -- Reference voltage is Vcc; select channel
    ports[ADMUX] := (1 << REFS0) \/ (BYTE pin)
    -- Enable ADC; enable interrupt; clock prescale 128
    ports[ADCSRA] := (BV (ADEN) \/ BV (ADIE)) \/ (7 << ADPS0)
    -- Disable digital inputs on all six ADC pins
    ports[DIDR0] := #3F
    WHILE TRUE
      SEQ
        req ? SIGNAL
        -- Start conversion
        ports[ADCSRA] := ports[ADCSRA] \/ BV (ADSC)

        -- serialWrite("Waiting for conversion...")
        -- Wait for conversion to complete
        INT t:
        wait.for.interrupt (VINTR.ADC, t)

        -- Read value
        -- (We can't do this by retyping ports, since that does a 16-bit read)
        [2]BYTE bytes RETYPES result:
        bytes[0], bytes[1] := ports[ADCL], ports[ADCH]

        val ! (INT result)
:


#ENDIF
--}}}
