.\" KRoC SDLRaster library overview page.  Last updated January 2006 Fred Barnes  <F.R.M.Barnes@kent.ac.uk>
.TH LIBSDLRASTER "3" "January 2006" "kroc 1.4.0" KRoC
.SH NAME
SDLRaster, SDLRasterClear, SDLRasterUpdate, SDLRasterUpdateBuf, SDLRasterAutoClose \- KRoC SDLRaster library
.SH SYNOPSIS
.B #INCLUDE \fB"sdlraster.inc\fB"\fR
.br
.B #USE \fB"sdlraster.lib\fB"\fR
.br
.B kroc -lsdlraster -lcif -lSDL
.PP
.BI "PROC SDLRaster (VAL []BYTE " dpyid ", VAL INT " width ", " height ", " nbuffers ", CHAN RASTER " in? ", " out! ", CHAN SDLEVENT " events! ", CHAN INT " control? ")"
.br
.BI "PROC SDLRasterClear ([][]INT " r ")"
.br
.BI "PROC SDLRasterUpdate ([][]INT " r ")"
.br
.BI "PROC SDLRasterUpdateBuf (VAL INT " bufnum ")"
.br
.BI "PROC SDLRasterAutoClose (CHAN SDLEVENT " events? ", CHAN INT " control! ")"
.PP
.BI "INT FUNCTION SDLEVENT.XPOS (VAL SDLEVENT " ev ")"
.br
.BI "INT FUNCTION SDLEVENT.YPOS (VAL SDLEVENT " ev ")"
.br
.BI "INT FUNCTION SDLEVENT.BUTTON (VAL SDLEVENT " ev ")"
.br
.BI "INT FUNCTION SDLEVENT.BSTATE (VAL SDLEVENT " ev ")"
.br
.BI "INT FUNCTION SDLEVENT.KSTATE (VAL SDLEVENT " ev ")"
.PP
.BI "DATA TYPE " RASTER " IS MOBILE [][]INT:"
.PP
.BI "DATA TYPE " SDLEVENT ""
.br
.BI "  RECORD"
.br
.BI "    INT " type ":"
.br
.BI "    INT " data ":"
.br
.BI ":"
.SH DESCRIPTION
The SDLRaster library provides basic framebuffer graphics to occam-pi programs using the
SDL (Simple DirectMedia Layer).  Full documentation can be found on the KRoC web-site at:
.PP
.BI "http://www.cs.kent.ac.uk/projects/ofa/kroc/sdlraster.html"
.SH AUTHOR
This manual page is maintained by Fred Barnes <F.R.M.Barnes@kent.ac.uk>

.SH "SEE ALSO"
.BR kroc (1)
.br
.BI "http://www.libsdl.org/"

