Import('env')
local = env.Clone()

local.Substitute('defaults.scm.in', 
            SUBST=dict(skroc_default_libs = 'forall',
                       prefix = '/home/foo'))

skroc = local.Mzc('skroc', 'skroc.ss')

env['SKROC'] = skroc
env['ENV']['SKROC'] = skroc
