Import('env')
local = env.Clone()

local.Subst('defaults.scm.in', 
            SUBST=dict(skroc_default_libs = '/dev/null',
                       prefix = '/home/foo'))

skroc = local.Mzc('skroc', 'skroc.ss')

env['SKROC'] = skroc
env['ENV']['SKROC'] = skroc
