#!/bin/bash 

# Source in everything we need--both the KRoC env and 
# variables for Arduino compilation and upload.

source avr-kroc-setup.sh
source arduinocc-environment.sh

# Sanity check
if [ "$1" == "" ]; then
  # Print reasonable documentation for the students
  echo
  echo "No port provided. On Ubuntu Linux, this is probably '/dev/ttyUSB0'."
  echo
  exit
fi

if [ "$2" == "firmware" ]; then
  echo "Uploading Transterpreter Virtual Machine"
  avrdude -C $TVM_AVRDUDE_CONF \
     $TVM_AVRDUDE_FIRMWARE_FLAGS \
    -P $1 -b $TVM_UPLOAD_RATE -c stk500v1 \
    -U flash:w:$TVM_ARDUINO_FIRMWARE
  exit
fi

if [ "$2" == "" ]; then
  # Print that they need the filename
  echo
  echo "You need to provide an occam program after the port."
  echo "For example:"
  echo
  echo "  arduinocc /dev/ttyUSB0 blink.occ"
  echo
  echo "occam programs always end with a .occ extension."
  echo
  exit
fi

PROGBASE=`basename $2 .occ`
PROGDIR=`dirname $2`
OCC="$PROGDIR/$PROGBASE.occ"
TBC="$PROGBASE.tbc"
HEX="$PROGBASE.hex"

# Another sanity check
if [ ! -f $OCC ]; then
  echo "Given: $OCC"
  echo "You did not provide an occam file for us to work with."
  exit
fi

UPLOAD_PORT=$1
AVRDUDE_FLAGS="$TVM_AVRDUDE_CODE_FLAGS -P $UPLOAD_PORT"
AVRDUDE_WRITE_OCCAM="-D -U flash:w:$HEX"

if [ -f $TBC ]; then
  echo "Removing old TBC file..."
  rm $TBC
fi


echo "Compiling..."
avr-occbuild \
  --search /opt/occam/share/tvm/avr-vtinclude \
  --search /opt/occam/share/tvm/avr-vtlib \
  --search /opt/occam/lib \
  -DF.CPU=$TVM_F_CPU --program $2

if [ $? -eq 0 ]; then

  if [ -f $HEX ]; then
    echo "Removing old HEX file..."
    rm $HEX
  fi

  if [ $? -eq 0 ]; then
    if [ -f $TBC ]; then
      echo "Converting to .hex..."
      binary-to-ihex $TVM_BYTECODE_ADDR $TBC $HEX
    else
      echo ".tbc file not generated or not found."
      exit
    fi
  fi


  if [ $? -eq 0 ]; then
    if [ -f $HEX ]; then
      echo "Uploading..."
      reset-arduino $UPLOAD_PORT
      avrdude -C $TVM_AVRDUDE_CONF $AVRDUDE_FLAGS $AVRDUDE_WRITE_OCCAM
    else
      echo ".hex file not generated or not found."
      exit
    fi
  fi

  if [ $? -eq 0 ]; then
    echo "Reading..."
    read-arduino $UPLOAD_PORT
  fi
fi
