#!/bin/bash
ROOT=/opt/occam/arduino
CONF=$ROOT/avrdude.conf
FLAGS="-V -F -p atmega328p"

if (test -n "$1") && (test -n "$2")
then
	PORT=$1
	HEX=$2
	# Reset the Arduino.
	$ROOT/bin/reset-arduino $PORT
	# Upload the code.
	avrdude -C $CONF $FLAGS -P $PORT -b 57600 -c stk500v1 -D -U flash:w:$HEX
	# Start listening to the serial port
	$ROOT/bin/read-arduino $PORT
else
	echo "Usage:"
	echo
	echo " upload-occam-program PORT PROGRAM"
	echo
	echo "where PORT may be '/dev/ttyUSB0' or similar"
	echo "where PROGRAM is the name of a compiled .hex file"
	echo
fi
