--** occam definitions for AVR processors.
-- @module avr

#IF NOT (DEFINED (AVR.MODULE))
#DEFINE AVR.MODULE

--{{{  per-MCU configuration
#DEFINE AVR.ATMEGA1280

#IF DEFINED (AVR.ATMEGA1280)
#INCLUDE "iomxx0_1.inc"
#ENDIF
--}}}

--* The CPU frequency in Hz.
VAL INT32 F.CPU IS ##F.CPU:

--* A value that's guaranteed to be higher than the highest port value defined
-- by this module.
--
-- This is for placing an array over all the ports:
--
-- [@code
-- PLACED [MAX.PORT]BYTE ports 0:
-- ports[PORTB] := 42
-- ]
-- FIXME: This has not yet been checked against the 1280.
VAL INT MAX.PORT IS #200:

--{{{  SFFI PROCs
#PRAGMA EXTERNAL "PROC C.tvmspecial.0.wait.for.interrupt (VAL INT interrupt, INT time) = 0"
INLINE PROC wait.for.interrupt (VAL INT interrupt, INT time)
  C.tvmspecial.0.wait.for.interrupt (interrupt, time)
:
--}}}

--{{{  interrupt numbers
-- From Page 105 of the 1280 manual.

-- From ATmega328p
-- VAL INT VINTR.TIMER1 IS 12:
--VAL INT VINTR.TIMER2 IS 6:

VAL INT VINTR.INT0          IS  #0002:  -- External Interrupt Request 0
VAL INT VINTR.INT1          IS  #0004:  --
VAL INT VINTR.INT2          IS  #0006:  --
VAL INT VINTR.INT3          IS  #0008:  --
VAL INT VINTR.INT4          IS  #000A:  --
VAL INT VINTR.INT5          IS  #000C:  --
VAL INT VINTR.INT6          IS  #000E:  --
VAL INT VINTR.INT7          IS  #0010:  --
VAL INT VINTR.PCINT0        IS  #0012:  -- Pin Change Interrupt Request 0
VAL INT VINTR.PCINT1        IS  #0014:  -- 
VAL INT VINTR.PCINT2        IS  #0016:  -- 
VAL INT VINTR.ADC           IS  #003A:  -- ADC Conversion Complete
VAL INT VINTR.USART.RX0     IS  #0032:  -- Rx Complete
VAL INT VINTR.USART.RX1     IS  #0048:  --
VAL INT VINTR.USART.RX2     IS  #0066:  --
VAL INT VINTR.USART.RX3     IS  #006C:  --
VAL INT VINTR.USART.UDRE0   IS  #0034:  -- Data Register Empty
VAL INT VINTR.USART.UDRE1   IS  #004A:  --
VAL INT VINTR.USART.UDRE2   IS  #0068:  --
VAL INT VINTR.USART.UDRE3   IS  #006E:  --
VAL INT VINTR.USART.TX0     IS  #0038:  -- Tx Complete
VAL INT VINTR.USART.TX1     IS  #004C:  --
VAL INT VINTR.USART.TX2     IS  #006A:  --
VAL INT VINTR.USART.TX3     IS  #0070:  --
--}}}

#ENDIF
