--** A weapper for platform-specific code on the ATmega1280.
-- @module 1280.avr

#IF NOT (DEFINED (AVR.MODULE))
#DEFINE AVR.MODULE

-- base, constants, and FFI must come first
#INCLUDE "base.module"
#INCLUDE "constants.module"
#INCLUDE "ffi.module"
#INCLUDE "chipmap.module"
-- These modules depend on base, constants, and FFI
#INCLUDE "pin.module"
#INCLUDE "usart.module"
#INCLUDE "pwm.common.module"
#INCLUDE "adc.module"

#ENDIF
