--
--      Copyright (C) 2009-2010   Matt Jadud
--      Copyright (C)      2010   Michael Andrew Pirrone-Brusse
--
--	This library is free software; you can redistribute it and/or
--	modify it under the terms of the GNU Lesser General Public
--	License as published by the Free Software Foundation; either
--	version 2 of the License, or (at your option) any later version.
--
--	This library is distributed in the hope that it will be useful,
--	but WITHOUT ANY WARRANTY; without even the implied warranty of
--	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
--	Lesser General Public License for more details.
--
--      You should have received a copy of the GNU General Public License
--      along with this program.  If not, see <http://www.gnu.org/licenses/>.

--** Symbolic arrays and FUNCTON(s) for mapping into General Purpose I/O
-- functionality on ATmega1280 based boards.
--
-- @module 1280.chipmap

#IF NOT (DEFINED (CHIPMAP.MODULE))
#DEFINE CHIPMAP.MODULE

VAL INT DDRX  IS -1:
VAL INT PORTX IS -1:
VAL INT PINX  IS -1:

--------- DDR.MAP --------------------------------------------
VAL []INT DDR.MAP IS [DDRG, DDRE, DDRE, DDRE, DDRE, DDRE, DDRE, DDRE, DDRE, DDRX, DDRX, DDRH, DDRH, DDRH, DDRH, DDRH, DDRH, DDRH, DDRB, DDRB, DDRB, DDRB, DDRB, DDRB, DDRB, DDRB, DDRH, DDRG, DDRG, DDRX, DDRX, DDRX, DDRX, DDRX, DDRL, DDRL, DDRL, DDRL, DDRL, DDRL, DDRL, DDRL, DDRD, DDRD, DDRD, DDRD, DDRD, DDRD, DDRD, DDRD, DDRG, DDRG, DDRC, DDRC, DDRC, DDRC, DDRC, DDRC, DDRC, DDRC, DDRX, DDRX, DDRJ, DDRJ, DDRJ, DDRJ, DDRJ, DDRJ, DDRJ, DDRG, DDRA, DDRA, DDRA, DDRA, DDRA, DDRA, DDRA, DDRA, DDRJ, DDRX, DDRX, DDRK, DDRK, DDRK, DDRK, DDRK, DDRK, DDRK, DDRK, DDRF, DDRF, DDRF, DDRF, DDRF, DDRF, DDRF, DDRF, DDRX, DDRX, DDRX]:

--------- PORT.MAP ---------------------------------------------------
VAL []INT PORT.MAP IS [PORTG, PORTE, PORTE, PORTE, PORTE, PORTE, PORTE, PORTE, PORTE, PORTX, PORTX, PORTH, PORTH, PORTH, PORTH, PORTH, PORTH, PORTH, PORTB, PORTB, PORTB, PORTB, PORTB, PORTB, PORTB, PORTB, PORTH, PORTG, PORTG, PORTX, PORTX, PORTX, PORTX, PORTX, PORTL, PORTL, PORTL, PORTL, PORTL, PORTL, PORTL, PORTL, PORTD, PORTD, PORTD, PORTD, PORTD, PORTD, PORTD, PORTD, PORTG, PORTG, PORTC, PORTC, PORTC, PORTC, PORTC, PORTC, PORTC, PORTC, PORTX, PORTX, PORTJ, PORTJ, PORTJ, PORTJ, PORTJ, PORTJ, PORTJ, PORTG, PORTA, PORTA, PORTA, PORTA, PORTA, PORTA, PORTA, PORTA, PORTJ, PORTX, PORTX, PORTK, PORTK, PORTK, PORTK, PORTK, PORTK, PORTK, PORTK, PORTF, PORTF, PORTF, PORTF, PORTF, PORTF, PORTF, PORTF, PORTX, PORTX, PORTX]:

--------- PIN.MAP ---------------------------------------------------
VAL []INT PIN.MAP IS [PING, PINE, PINE, PINE, PINE, PINE, PINE, PINE, PINE, PINX, PINX, PINH, PINH, PINH, PINH, PINH, PINH, PINH, PINB, PINB, PINB, PINB, PINB, PINB, PINB, PINB, PINH, PING, PING, PINX, PINX, PINX, PINX, PINX, PINL, PINL, PINL, PINL, PINL, PINL, PINL, PINL, PIND, PIND, PIND, PIND, PIND, PIND, PIND, PIND, PING, PING, PINC, PINC, PINC, PINC, PINC, PINC, PINC, PINC, PINX, PINX, PINJ, PINJ, PINJ, PINJ, PINJ, PINJ, PINJ, PING, PINA, PINA, PINA, PINA, PINA, PINA, PINA, PINA, PINJ, PINX, PINX, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINF, PINF, PINF, PINF, PINF, PINF, PINF, PINF, PINX, PINX, PINX]:

--------- BIT.MAP ---------------------------------------------------
VAL []INT BIT.MAP IS [5, 0, 1, 2, 3, 4, 5, 6, 7, -1, -1, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 7, 7, 3, 4, -1, -1, -1, -1, -1, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 0, 1, 2, 3, 4, 5, 6, 7, -1, -1, 0, 1, 2, 3, 4, 5, 6, 2, 7, 6, 5, 4, 3, 2, 1, 0, 7, -1, -1, 7, 6, 5, 4, 3, 2, 1, 0, 7, 6, 5, 4, 3, 2, 1, 0, -1, -1, -1]:

--FIXME: mjadud It would be nice if this wasn't duplicated in each architecture

--* Looks up the various General Purpose I/O registers connected to the given
-- [@em AVR] pin.
--
-- @param avr.pin The [@em AVR] pin controlled by the given returns.
-- @returns ddr, port, pin The various control registers that effects the
--   behaviour of the given pin.
-- @return bit The specific bit of the control registers that alters the
--   behavior of the given AVR pin.
INT, INT, INT, INT FUNCTION chip.to.gpio (VAL INT avr.pin) 
  INT ddr, port, pin, bit:
  VALOF
    SEQ
      -- AVR pins are numbered starting from 1...
      -- We need to subtract 1 to index into the arrays.
      ddr  := DDR.MAP[avr.pin - 1]
      port := PORT.MAP[avr.pin - 1]
      pin  := PIN.MAP[avr.pin - 1]
      bit  := BIT.MAP[avr.pin - 1]
    RESULT ddr, port, pin, bit
:

#ENDIF
