--
--	Copyright (C) 2009-2010   Christian Jacobsen
--      Copyright (C) 2009-2010   Matt Jadud
--      Copyright (C) 2009-2010   Adam Sampson
--
--	This library is free software; you can redistribute it and/or
--	modify it under the terms of the GNU Lesser General Public
--	License as published by the Free Software Foundation; either
--	version 2 of the License, or (at your option) any later version.
--
--	This library is distributed in the hope that it will be useful,
--	but WITHOUT ANY WARRANTY; without even the implied warranty of
--	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
--	Lesser General Public License for more details.
--
--      You should have received a copy of the GNU General Public License
--      along with this program.  If not, see <http://www.gnu.org/licenses/>.
--
--** Foreign functions ofr hte 1280 wrapper
-- @module 1280.ffi

#IF NOT (DEFINED (FFI.MODULE))
#DEFINE FFI.MODULE

--{{{  SFFI PROCs
#PRAGMA EXTERNAL "PROC C.tvmspecial.0.wait.for.interrupt (VAL INT interrupt, INT time) = 0"
INLINE PROC wait.for.interrupt (VAL INT interrupt, INT time)
  C.tvmspecial.0.wait.for.interrupt (interrupt, time)
:
--}}}

#ENDIF
