--** Pulse Width Modulation board-specific helper functions for the ATmega1280
-- @module pwm_arch


#IF NOT (DEFINED (PWMARCH.MODULE))
#DEFINE PWMARCH.MODULE

--This is a stub. It will change soon.

INT, INT, INT, INT FUNCTION pwm8.lookup (VAL INT pin)
  INT a, b, c, d:
  VALOF
    a, b, c, d := 1, 2, 3, 4
    RESULT a, b, c, d
:

INT, INT, INT, INT FUNCTION pwm16.lookup (VAL INT pin)
  INT a, b, c, d:
  VALOF
    a, b, c, d := 1, 2, 3, 4
    RESULT a, b, c, d
:

INT FUNCTION pwm8.TCCRnB.helper (VAL INT prescale)
  INT a:
  VALOF
    a := 1
    RESULT a
:

INT FUNCTION pwm16.TCCRnB.helper (VAL INT prescale)
  INT a:
  VALOF
    a := 1
    RESULT a
:

INT FUNCTION pwm8.compare.lookup (VAL INT pin)
  INT a:
  VALOF
    a := 1
    RESULT a
:

INT FUNCTION pwm16.compare.lookup (VAL INT pin)
  INT a:
  VALOF
    a := 1
    RESULT a
:

INT FUNCTION pwm16.ICRn.lookup (VAL INT pin)
  INT a:
  VALOF
    a := 1
    RESULT a
: 

#ENDIF
