Import('env')
local = env.Clone()

# @KROC_HOST_OS@, @prefix@, @KROC_ARCHBINDIR@, @KROC_ARCHLIBDIR@,
# @KROC_KROCDIR@, @KROC_EXAMPLESDIR@

# @TVM_BINDIR@, @TVM_LIBDIR@, @TVM_EXAMPLESDIR@

local.Subst('occbuild', 'occbuild.in', SUBST=dict(TVM_LIBDIR='moo'))
