/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_transterpreter_jeditsparkleplugin_JEditSparklePlugin */

#ifndef _Included_org_transterpreter_jeditsparkleplugin_JEditSparklePlugin
#define _Included_org_transterpreter_jeditsparkleplugin_JEditSparklePlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_transterpreter_jeditsparkleplugin_JEditSparklePlugin
 * Method:    initSparkle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_transterpreter_jeditsparkleplugin_JEditSparklePlugin_initSparkle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
